preload = ~/Pictures/Wallpaper/gear5-cat-minimal.png
preload = ~/Pictures/Wallpaper/gear5-catppuccin.png
preload = ~/Pictures/Wallpaper/gear5-cat-frappe.png
preload = ~/Pictures/Wallpaper/tux-cat.jpg
wallpaper = eDP-1, ~/Pictures/Wallpaper/tux-cat.jpg
